---
- name: Install Apache
  hosts: serveurs
  become: yes  # Utilise les privilèges root
  tasks:

    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running and enabled
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        name: "Apache Full"
