---
- name: Installation de Semaphore
  hosts: gcp
  become: yes

  tasks:
    - name: Update
      apt:
        update_cache: yes

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Ouvrir le port 3000 du firewall
      ufw:
        rule: allow
        port: 3000
        proto: tcp

    - name: enable le UFW
      ufw:
        state: enabled
        policy: allow

    - name: Install Snapd
      apt:
        name: snapd
        state: present

    - name: Enable Snapd service
      systemd:
        name: snapd
        enabled: yes
        state: started


    - name: Install Semaphore
      snap:
        name: semaphore
        state: present

    - name: Start Semaphore service
      shell: sudo snap start semaphore
      args:
        executable: /bin/bash

